apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: godeploy
        image: mbr3d4/godeploy:latest
        ports:
        - containerPort: 8080